### ISSUE TITLE
data directory "/var/lib/postgresql/data" has wrong ownership

### ISSUE THREAD

**Issue by jralfonsog** [sertansenturk/cookiecutter-ds-docker#56] opened 2020-07-26 00:11 UTC
**One-line summary (optional)**
When building, postgresql container gives the error: `data directory "/var/lib/postgresql/data" has wrong ownership`

**Steps to Reproduce**
Run `make` or `make all`

** Include specs (OS, Python version, code commit hash or release version), if useful **
Linux Mint 19.3, Python 3.7.7

**Outcome**
```
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  | 
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  | 
postgres_1  | Data page checksums are disabled.
postgres_1  | 
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | selecting default max_connections ... 20
postgres_1  | selecting default shared_buffers ... 400kB
postgres_1  | selecting default time zone ... Etc/UTC
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... 2020-07-25 18:03:19.812 UTC [74] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
postgres_1  | 2020-07-25 18:03:19.812 UTC [74] HINT:  The server must be started by the user that owns the data directory.
postgres_1  | child process exited with exit code 1
postgres_1  | initdb: removing contents of data directory "/var/lib/postgresql/data"
```

**Comment by sertansenturk** [comment] 2020-07-29 09:36
Thank you @jralfonsog for reporting this bug.

This is a project I work on my free time, so I am sure there are problems like this one which I fixed in Ubuntu but does not work universally.

I will take a look at it this weekend, and try to understand the problem. In the meantime, can you tell me the user and group id of the username you ran the docker-compose stack, e.g. by running `id` on the terminal?

**Comment by jralfonsog** [comment] 2020-07-29 21:33
Hi, Sertan.

Yeah, I know. Just pointing it out, although maybe there's something I'm
doing wrong...

*id* output would be:

> uid=1000(jralfonsog) gid=1000(jralfonsog)
> grupos=1000(jralfonsog),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),50(staff),112(lpadmin),128(sambashare),999(docker)


I've asked on docker forum in the meantime, and they've told me to use
named volumes instead of host paths... but it isn't working (now it just
says project_postgres_1 exited with code 1, without any more trace).

It's a cool and complete template, Sertan. Keep up the good work :)

By the way, I'm using Docker v19.03.12, build 48a66213fe on Linux Mint 19.03, in case it helps.

**Comment by jralfonsog** [comment] 2020-07-29 22:54
Hi again, Sertan.

Quick update. I found where the problem was, I was testing it on a NTFS mapped folder... It works perfectly if I use an Ext4.

Thanks anyway! :)

**Comment by sertansenturk** [comment] 2020-07-30 11:00
Ohh, I see! It is good to know. I can open a known issues section in the README and include the NTFS problem. Or if you'd like to contribute directly, you can also open a PR too :) 

Either way, I will close the issue, once the issue is documented in the README file.

Thank you for your compliments and your help! Let's see where the repo will take itself.

**Comment by jralfonsog** [comment] 2020-07-30 21:57
Oh, go ahead and open the section. I'll probably play some more, so I'll let you know/do a PR if I see anything else :)

**Comment by sertansenturk** [comment] 2020-08-07 11:06
I created a PR, which documents the issue: https://github.com/sertansenturk/cookiecutter-ds-docker/pull/57

@jralfonsog can you take a look at the PR, whenever you have time? I can add you repo's contributors, in case you would like to give proper approval, or make modifications by yourself.

PS: I have also added your name in the documentation ([link](https://github.com/sertansenturk/cookiecutter-ds-docker/blob/22ef88853a3ecbe662abe01f8033ab5d3132b1d9/docs/05_credits.rst)). If you want to modify the text or if you want me to remove your name, please let me know.

**Comment by jralfonsog** [comment] 2020-08-07 11:15
> I created a PR, which documents the issue: #57
> 
> @jralfonsog can you take a look at the PR, whenever you have time? I can add you repo's contributors, in case you would like to give proper approval, or make modifications by yourself.
> 
> PS: I have also added your name in the documentation ([link](https://github.com/sertansenturk/cookiecutter-ds-docker/blob/22ef88853a3ecbe662abe01f8033ab5d3132b1d9/docs/05_credits.rst)). If you want to modify the text or if you want me to remove your name, please let me know.

It's perfect this way, thanks! I think I've given approval properly, but I keep seeing the "Review required" message.

**Closed as completed** 2020-08-07 11:19 UTC
Labels: Bug

**Comment by sertansenturk** [comment] 2020-08-07 11:20
I think it's about having writer permissions. I can still merge, it's not a problem. 

The issue is closed. Thanks for your report and help!

**Comment by cn00** [comment] 2022-09-15 05:20
The problem is still exist on pg14, but I find an unusual solution on docker-compose,  and test for pg11 and pg14:
- add `user: 999:999 # postgres user ` in docker-compose.yml
- run `docker-compose run postgres bash`
- run `docker-compose up -d`

but I don't know why it works😅

**Comment by UgurGumushan** [comment] 2022-10-09 12:41
Disabling VirtioFS on docker resolved the issue for me.
MacOS, M1

**Comment by realies** [comment] 2022-10-28 17:49
Thanks, @UgurGumushan, this took me a while to narrow down.

**Comment by jsifantu** [comment] 2022-11-08 14:24
Yes, thank you  @UgurGumusha for the suggestion!!
